spring:
  application:
    name: api-service
  thymeleaf:
    check-template-location: false
  datasource:
    url: jdbc:postgresql://localhost:5432/vendoria
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true

server:
  port: 5000

eureka:
  client:
    enabled: true