spring:
  application:
    name: vendoria-bff

server:
  port: 3000

eureka:
  client:
    enabled: true

security:
  user:
    name: 1
    password: 1
  app:
    authentication:
      cookie: "ud"

app:
  api:
    vendoria: "/api"

    path:
      auth:
        register: "/register"
        signin: "/signin"
        logout: "/logout"

      users:
        getUser: "/user"

views:
  app:
    error: "/path/to/error/page"

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full
  compression:
    request:
      enabled: true
    response:
      enabled: true

logging:
  level:
    com.vendoria.bff.feign: DEBUG